//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moleQule.Face.Application.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("moleQule.Face.Application.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Aceptar {
            get {
                object obj = ResourceManager.GetObject("Aceptar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap acreedor {
            get {
                object obj = ResourceManager.GetObject("acreedor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap acreedor_activo {
            get {
                object obj = ResourceManager.GetObject("acreedor_activo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap acreedor_baja {
            get {
                object obj = ResourceManager.GetObject("acreedor_baja", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap acta_48 {
            get {
                object obj = ResourceManager.GetObject("acta_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Actualizar {
            get {
                object obj = ResourceManager.GetObject("Actualizar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap albaran_32 {
            get {
                object obj = ResourceManager.GetObject("albaran_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap albaran_emitido {
            get {
                object obj = ResourceManager.GetObject("albaran_emitido", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap albaran_emitido_abierto {
            get {
                object obj = ResourceManager.GetObject("albaran_emitido_abierto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap albaran_emitido_facturado {
            get {
                object obj = ResourceManager.GetObject("albaran_emitido_facturado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap albaran_recibido {
            get {
                object obj = ResourceManager.GetObject("albaran_recibido", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap albaran_recibido_abierto {
            get {
                object obj = ResourceManager.GetObject("albaran_recibido_abierto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap albaran_recibido_facturado {
            get {
                object obj = ResourceManager.GetObject("albaran_recibido_facturado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Alumnos {
            get {
                object obj = ResourceManager.GetObject("Alumnos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap apunte_banco {
            get {
                object obj = ResourceManager.GetObject("apunte_banco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap area_48 {
            get {
                object obj = ResourceManager.GetObject("area_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap auditoria_48 {
            get {
                object obj = ResourceManager.GetObject("auditoria_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap backup {
            get {
                object obj = ResourceManager.GetObject("backup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap balance {
            get {
                object obj = ResourceManager.GetObject("balance", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap borrar_16 {
            get {
                object obj = ResourceManager.GetObject("borrar_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap browse_16 {
            get {
                object obj = ResourceManager.GetObject("browse_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap caja_32 {
            get {
                object obj = ResourceManager.GetObject("caja_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap caja_tickets {
            get {
                object obj = ResourceManager.GetObject("caja_tickets", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap calendar {
            get {
                object obj = ResourceManager.GetObject("calendar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cargo {
            get {
                object obj = ResourceManager.GetObject("cargo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cerrar {
            get {
                object obj = ResourceManager.GetObject("Cerrar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cierre_caja {
            get {
                object obj = ResourceManager.GetObject("cierre_caja", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap claseauditoria_48 {
            get {
                object obj = ResourceManager.GetObject("claseauditoria_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cliente {
            get {
                object obj = ResourceManager.GetObject("cliente", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cliente_activo {
            get {
                object obj = ResourceManager.GetObject("cliente_activo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cliente_baja {
            get {
                object obj = ResourceManager.GetObject("cliente_baja", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cobro {
            get {
                object obj = ResourceManager.GetObject("cobro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cobro_cliente {
            get {
                object obj = ResourceManager.GetObject("cobro_cliente", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cobro_factura_emitida {
            get {
                object obj = ResourceManager.GetObject("cobro_factura_emitida", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cobro_todos {
            get {
                object obj = ResourceManager.GetObject("cobro_todos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cuenta_bancaria {
            get {
                object obj = ResourceManager.GetObject("cuenta_bancaria", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap curso_48 {
            get {
                object obj = ResourceManager.GetObject("curso_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cursos {
            get {
                object obj = ResourceManager.GetObject("Cursos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap delete_32 {
            get {
                object obj = ResourceManager.GetObject("delete_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Delete2 {
            get {
                object obj = ResourceManager.GetObject("Delete2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap departamento_48 {
            get {
                object obj = ResourceManager.GetObject("departamento_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Derecha {
            get {
                object obj = ResourceManager.GetObject("Derecha", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap despachante {
            get {
                object obj = ResourceManager.GetObject("despachante", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap despachante_32 {
            get {
                object obj = ResourceManager.GetObject("despachante_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap despachante_activo {
            get {
                object obj = ResourceManager.GetObject("despachante_activo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap despachante_baja {
            get {
                object obj = ResourceManager.GetObject("despachante_baja", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap discrepancia {
            get {
                object obj = ResourceManager.GetObject("discrepancia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Disponibilidad {
            get {
                object obj = ResourceManager.GetObject("Disponibilidad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document {
            get {
                object obj = ResourceManager.GetObject("document", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap documento {
            get {
                object obj = ResourceManager.GetObject("documento", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap documentos_48 {
            get {
                object obj = ResourceManager.GetObject("documentos_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Edit {
            get {
                object obj = ResourceManager.GetObject("Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap edit_32 {
            get {
                object obj = ResourceManager.GetObject("edit_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Emitir {
            get {
                object obj = ResourceManager.GetObject("Emitir", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap empleado {
            get {
                object obj = ResourceManager.GetObject("empleado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap empleado_activo {
            get {
                object obj = ResourceManager.GetObject("empleado_activo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap empleado_activo1 {
            get {
                object obj = ResourceManager.GetObject("empleado_activo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap empleado_baja {
            get {
                object obj = ResourceManager.GetObject("empleado_baja", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap empleado_baja1 {
            get {
                object obj = ResourceManager.GetObject("empleado_baja1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap empleado1 {
            get {
                object obj = ResourceManager.GetObject("empleado1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap empresa {
            get {
                object obj = ResourceManager.GetObject("empresa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Empresas {
            get {
                object obj = ResourceManager.GetObject("Empresas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Examen {
            get {
                object obj = ResourceManager.GetObject("Examen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap expediente {
            get {
                object obj = ResourceManager.GetObject("expediente", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap extracto_tarjeta {
            get {
                object obj = ResourceManager.GetObject("extracto_tarjeta", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap factura_emitida {
            get {
                object obj = ResourceManager.GetObject("factura_emitida", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap factura_emitida_32 {
            get {
                object obj = ResourceManager.GetObject("factura_emitida_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap factura_emitida_cobrada {
            get {
                object obj = ResourceManager.GetObject("factura_emitida_cobrada", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap factura_emitida_pendiente {
            get {
                object obj = ResourceManager.GetObject("factura_emitida_pendiente", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap factura_recibida {
            get {
                object obj = ResourceManager.GetObject("factura_recibida", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap factura_recibida_32 {
            get {
                object obj = ResourceManager.GetObject("factura_recibida_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap factura_recibida_pagada {
            get {
                object obj = ResourceManager.GetObject("factura_recibida_pagada", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap factura_recibida_pendiente {
            get {
                object obj = ResourceManager.GetObject("factura_recibida_pendiente", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap familia {
            get {
                object obj = ResourceManager.GetObject("familia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap filter_on_16 {
            get {
                object obj = ResourceManager.GetObject("filter_on_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap form_yellow {
            get {
                object obj = ResourceManager.GetObject("form_yellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap form_yellow1 {
            get {
                object obj = ResourceManager.GetObject("form_yellow1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap form_yellow2 {
            get {
                object obj = ResourceManager.GetObject("form_yellow2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gasto_general {
            get {
                object obj = ResourceManager.GetObject("gasto_general", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gasto_impuesto {
            get {
                object obj = ResourceManager.GetObject("gasto_impuesto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gasto_nomina {
            get {
                object obj = ResourceManager.GetObject("gasto_nomina", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gastos {
            get {
                object obj = ResourceManager.GetObject("gastos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Hangar {
            get {
                object obj = ResourceManager.GetObject("Hangar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Horarios {
            get {
                object obj = ResourceManager.GetObject("Horarios", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Imprimir {
            get {
                object obj = ResourceManager.GetObject("Imprimir", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap impuesto {
            get {
                object obj = ResourceManager.GetObject("impuesto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap incidencia {
            get {
                object obj = ResourceManager.GetObject("incidencia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap index {
            get {
                object obj = ResourceManager.GetObject("index", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap informe {
            get {
                object obj = ResourceManager.GetObject("informe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Instructor {
            get {
                object obj = ResourceManager.GetObject("Instructor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap inventario_valorado {
            get {
                object obj = ResourceManager.GetObject("inventario_valorado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Izquierda {
            get {
                object obj = ResourceManager.GetObject("Izquierda", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kit {
            get {
                object obj = ResourceManager.GetObject("kit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Liberar {
            get {
                object obj = ResourceManager.GetObject("Liberar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap linea_caja {
            get {
                object obj = ResourceManager.GetObject("linea_caja", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap localidad {
            get {
                object obj = ResourceManager.GetObject("localidad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap login {
            get {
                object obj = ResourceManager.GetObject("login", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Logotipos {
            get {
                object obj = ResourceManager.GetObject("Logotipos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap material_48 {
            get {
                object obj = ResourceManager.GetObject("material_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MaterialDocente {
            get {
                object obj = ResourceManager.GetObject("MaterialDocente", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap microexpediente {
            get {
                object obj = ResourceManager.GetObject("microexpediente", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap modelo {
            get {
                object obj = ResourceManager.GetObject("modelo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Modulos {
            get {
                object obj = ResourceManager.GetObject("Modulos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap molequle {
            get {
                object obj = ResourceManager.GetObject("molequle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap naviera_48 {
            get {
                object obj = ResourceManager.GetObject("naviera_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap naviera_activo {
            get {
                object obj = ResourceManager.GetObject("naviera_activo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap naviera_baja {
            get {
                object obj = ResourceManager.GetObject("naviera_baja", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Notas {
            get {
                object obj = ResourceManager.GetObject("Notas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap notificaciones {
            get {
                object obj = ResourceManager.GetObject("notificaciones", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap obra {
            get {
                object obj = ResourceManager.GetObject("obra", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ordenar_16 {
            get {
                object obj = ResourceManager.GetObject("ordenar_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap order_32 {
            get {
                object obj = ResourceManager.GetObject("order_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap otras_tablas_48 {
            get {
                object obj = ResourceManager.GetObject("otras_tablas_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap package {
            get {
                object obj = ResourceManager.GetObject("package", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pago {
            get {
                object obj = ResourceManager.GetObject("pago", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pago_acreedor {
            get {
                object obj = ResourceManager.GetObject("pago_acreedor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pago_factura_recibida {
            get {
                object obj = ResourceManager.GetObject("pago_factura_recibida", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pago_gasto {
            get {
                object obj = ResourceManager.GetObject("pago_gasto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pago_nomina {
            get {
                object obj = ResourceManager.GetObject("pago_nomina", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pago_todos {
            get {
                object obj = ResourceManager.GetObject("pago_todos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Partes {
            get {
                object obj = ResourceManager.GetObject("Partes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pedido_48 {
            get {
                object obj = ResourceManager.GetObject("pedido_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pedido_cliente {
            get {
                object obj = ResourceManager.GetObject("pedido_cliente", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pedido_proveedor {
            get {
                object obj = ResourceManager.GetObject("pedido_proveedor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap plananual_48 {
            get {
                object obj = ResourceManager.GetObject("plananual_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PlanEstudios {
            get {
                object obj = ResourceManager.GetObject("PlanEstudios", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PlanExtra {
            get {
                object obj = ResourceManager.GetObject("PlanExtra", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap precios {
            get {
                object obj = ResourceManager.GetObject("precios", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Preguntas {
            get {
                object obj = ResourceManager.GetObject("Preguntas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap prestamo {
            get {
                object obj = ResourceManager.GetObject("prestamo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap presupuesto {
            get {
                object obj = ResourceManager.GetObject("presupuesto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap presupuesto_32 {
            get {
                object obj = ResourceManager.GetObject("presupuesto_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Print {
            get {
                object obj = ResourceManager.GetObject("Print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap producto {
            get {
                object obj = ResourceManager.GetObject("producto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Promociones {
            get {
                object obj = ResourceManager.GetObject("Promociones", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Proponer {
            get {
                object obj = ResourceManager.GetObject("Proponer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap proveedor {
            get {
                object obj = ResourceManager.GetObject("proveedor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap proveedor_activo {
            get {
                object obj = ResourceManager.GetObject("proveedor_activo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap proveedor_baja {
            get {
                object obj = ResourceManager.GetObject("proveedor_baja", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap proveedor1 {
            get {
                object obj = ResourceManager.GetObject("proveedor1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap puertos {
            get {
                object obj = ResourceManager.GetObject("puertos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Quitar {
            get {
                object obj = ResourceManager.GetObject("Quitar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap registro {
            get {
                object obj = ResourceManager.GetObject("registro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap remesa_nomina {
            get {
                object obj = ResourceManager.GetObject("remesa_nomina", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Replace {
            get {
                object obj = ResourceManager.GetObject("Replace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap report_48 {
            get {
                object obj = ResourceManager.GetObject("report_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Resumen {
            get {
                object obj = ResourceManager.GetObject("Resumen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap salir {
            get {
                object obj = ResourceManager.GetObject("salir", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Seleccionar_16 {
            get {
                object obj = ResourceManager.GetObject("Seleccionar_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap select_16 {
            get {
                object obj = ResourceManager.GetObject("select_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap serie {
            get {
                object obj = ResourceManager.GetObject("serie", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shield {
            get {
                object obj = ResourceManager.GetObject("shield", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stock {
            get {
                object obj = ResourceManager.GetObject("stock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap store {
            get {
                object obj = ResourceManager.GetObject("store", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap submit {
            get {
                object obj = ResourceManager.GetObject("submit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap target {
            get {
                object obj = ResourceManager.GetObject("target", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tarjeta_credito {
            get {
                object obj = ResourceManager.GetObject("tarjeta_credito", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ticket {
            get {
                object obj = ResourceManager.GetObject("ticket", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tipo_gasto {
            get {
                object obj = ResourceManager.GetObject("tipo_gasto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tpv {
            get {
                object obj = ResourceManager.GetObject("tpv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap transportista {
            get {
                object obj = ResourceManager.GetObject("transportista", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap transportista_48 {
            get {
                object obj = ResourceManager.GetObject("transportista_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap transportista_activo {
            get {
                object obj = ResourceManager.GetObject("transportista_activo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap transportista_activo1 {
            get {
                object obj = ResourceManager.GetObject("transportista_activo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap transportista_baja {
            get {
                object obj = ResourceManager.GetObject("transportista_baja", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap transportista_baja1 {
            get {
                object obj = ResourceManager.GetObject("transportista_baja1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap transportista1 {
            get {
                object obj = ResourceManager.GetObject("transportista1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap traspaso_banco {
            get {
                object obj = ResourceManager.GetObject("traspaso_banco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ver_16 {
            get {
                object obj = ResourceManager.GetObject("ver_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap View {
            get {
                object obj = ResourceManager.GetObject("View", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap view_32 {
            get {
                object obj = ResourceManager.GetObject("view_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
