//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moleQule.Face.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("moleQule.Face.Application.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acerca de....
        /// </summary>
        internal static string ABOUT_TITLE {
            get {
                return ResourceManager.GetString("ABOUT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actas del Comité de Calidad.
        /// </summary>
        internal static string ACTA_COMITE {
            get {
                return ResourceManager.GetString("ACTA_COMITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Acta del Comité de Calidad:.
        /// </summary>
        internal static string ACTA_COMITE_ADD_TITLE {
            get {
                return ResourceManager.GetString("ACTA_COMITE_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Acta del Comité de Calidad:.
        /// </summary>
        internal static string ACTA_COMITE_EDIT_TITLE {
            get {
                return ResourceManager.GetString("ACTA_COMITE_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Actas del Comité de Calidad:.
        /// </summary>
        internal static string ACTA_COMITE_FIND_TITLE {
            get {
                return ResourceManager.GetString("ACTA_COMITE_FIND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviso.
        /// </summary>
        internal static string ADVISE_TITLE {
            get {
                return ResourceManager.GetString("ADVISE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Albarán:.
        /// </summary>
        internal static string ALBARAN_ADD_TITLE {
            get {
                return ResourceManager.GetString("ALBARAN_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles del Albarán:.
        /// </summary>
        internal static string ALBARAN_DETAIL_TITLE {
            get {
                return ResourceManager.GetString("ALBARAN_DETAIL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Albarán.
        /// </summary>
        internal static string ALBARAN_EDIT_TITLE {
            get {
                return ResourceManager.GetString("ALBARAN_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir Almacén.
        /// </summary>
        internal static string ALMACEN_ADD_TITLE {
            get {
                return ResourceManager.GetString("ALMACEN_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles del Almacén.
        /// </summary>
        internal static string ALMACEN_DETAIL_TITLE {
            get {
                return ResourceManager.GetString("ALMACEN_DETAIL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Almacén.
        /// </summary>
        internal static string ALMACEN_EDIT_TITLE {
            get {
                return ResourceManager.GetString("ALMACEN_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Alumno:.
        /// </summary>
        internal static string ALUMNO_ADD_TITLE {
            get {
                return ResourceManager.GetString("ALUMNO_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Alumno:.
        /// </summary>
        internal static string ALUMNO_EDIT_TITLE {
            get {
                return ResourceManager.GetString("ALUMNO_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevas Respuestas de Alumno:.
        /// </summary>
        internal static string ALUMNO_EXAMEN_ADD_TITLE {
            get {
                return ResourceManager.GetString("ALUMNO_EXAMEN_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Respuestas de Alumno:.
        /// </summary>
        internal static string ALUMNO_EXAMEN_EDIT_TITLE {
            get {
                return ResourceManager.GetString("ALUMNO_EXAMEN_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Alumnos:.
        /// </summary>
        internal static string ALUMNO_FIND_TITLE {
            get {
                return ResourceManager.GetString("ALUMNO_FIND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alumnos.
        /// </summary>
        internal static string ALUMNOS {
            get {
                return ResourceManager.GetString("ALUMNOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iQ Hangar.
        /// </summary>
        internal static string APP_TITLE {
            get {
                return ResourceManager.GetString("APP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Área:.
        /// </summary>
        internal static string AREA_ADD_TITLE {
            get {
                return ResourceManager.GetString("AREA_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Área:.
        /// </summary>
        internal static string AREA_EDIT_TITLE {
            get {
                return ResourceManager.GetString("AREA_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localizar Área:.
        /// </summary>
        internal static string AREA_FIND_TITLE {
            get {
                return ResourceManager.GetString("AREA_FIND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Áreas.
        /// </summary>
        internal static string AREAS {
            get {
                return ResourceManager.GetString("AREAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partes de Asistencia.
        /// </summary>
        internal static string ASISTENCIAS {
            get {
                return ResourceManager.GetString("ASISTENCIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditorías.
        /// </summary>
        internal static string AUDITORIA {
            get {
                return ResourceManager.GetString("AUDITORIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Auditoría:.
        /// </summary>
        internal static string AUDITORIA_ADD_TITLE {
            get {
                return ResourceManager.GetString("AUDITORIA_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Auditoría:.
        /// </summary>
        internal static string AUDITORIA_EDIT_TITLE {
            get {
                return ResourceManager.GetString("AUDITORIA_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Auditorías:.
        /// </summary>
        internal static string AUDITORIA_FIND_TITLE {
            get {
                return ResourceManager.GetString("AUDITORIA_FIND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviso.
        /// </summary>
        internal static string AVISO {
            get {
                return ResourceManager.GetString("AVISO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir Caja.
        /// </summary>
        internal static string CAJA_ADD_TITLE {
            get {
                return ResourceManager.GetString("CAJA_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles de la Caja.
        /// </summary>
        internal static string CAJA_DETAIL_TITLE {
            get {
                return ResourceManager.GetString("CAJA_DETAIL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Caja.
        /// </summary>
        internal static string CAJA_EDIT_TITLE {
            get {
                return ResourceManager.GetString("CAJA_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir Capacidad:.
        /// </summary>
        internal static string CAPACIDAD_TITLE {
            get {
                return ResourceManager.GetString("CAPACIDAD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargos de Contactos.
        /// </summary>
        internal static string CARGO_TITLE {
            get {
                return ResourceManager.GetString("CARGO_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clases de Auditorías.
        /// </summary>
        internal static string CLASE_AUDITORIA {
            get {
                return ResourceManager.GetString("CLASE_AUDITORIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Clase de Auditoría:.
        /// </summary>
        internal static string CLASE_AUDITORIA_ADD_TITLE {
            get {
                return ResourceManager.GetString("CLASE_AUDITORIA_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Clase de Auditoría:.
        /// </summary>
        internal static string CLASE_AUDITORIA_EDIT_TITLE {
            get {
                return ResourceManager.GetString("CLASE_AUDITORIA_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Clases de Auditorías:.
        /// </summary>
        internal static string CLASE_AUDITORIA_FIND_TITLE {
            get {
                return ResourceManager.GetString("CLASE_AUDITORIA_FIND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar Clase:.
        /// </summary>
        internal static string CLASE_HORARIO_TITLE {
            get {
                return ResourceManager.GetString("CLASE_HORARIO_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clases Ordenadas:.
        /// </summary>
        internal static string CLASES_ORDENADAS_VIEW_TITLE {
            get {
                return ResourceManager.GetString("CLASES_ORDENADAS_VIEW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Cliente:.
        /// </summary>
        internal static string CLIENTE_ADD_TITLE {
            get {
                return ResourceManager.GetString("CLIENTE_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle de Cliente:.
        /// </summary>
        internal static string CLIENTE_DETAIL_TITLE {
            get {
                return ResourceManager.GetString("CLIENTE_DETAIL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Cliente:.
        /// </summary>
        internal static string CLIENTE_EDIT_TITLE {
            get {
                return ResourceManager.GetString("CLIENTE_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Clientes:.
        /// </summary>
        internal static string CLIENTE_FIND_TITLE {
            get {
                return ResourceManager.GetString("CLIENTE_FIND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es preciso cerrar sesión antes de configurar el servidor.  ¿Desea continuar?.
        /// </summary>
        internal static string CLOSE_SESSION {
            get {
                return ResourceManager.GetString("CLOSE_SESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comunicado de Auditoría.
        /// </summary>
        internal static string COMUNICADO_AUDITORIA_TITLE {
            get {
                return ResourceManager.GetString("COMUNICADO_AUDITORIA_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albaranes:.
        /// </summary>
        internal static string CONCEPTO_ALBARAN_TITLE {
            get {
                return ResourceManager.GetString("CONCEPTO_ALBARAN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Concepto de Factura.
        /// </summary>
        internal static string CONCEPTO_EDIT_TITLE {
            get {
                return ResourceManager.GetString("CONCEPTO_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concepto Factura.
        /// </summary>
        internal static string CONCEPTO_FACTURA_TITLE {
            get {
                return ResourceManager.GetString("CONCEPTO_FACTURA_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concepto Libre.
        /// </summary>
        internal static string CONCEPTO_LIBRE_TITLE {
            get {
                return ResourceManager.GetString("CONCEPTO_LIBRE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurar Servidor:.
        /// </summary>
        internal static string CONFIGURE_SERVER {
            get {
                return ResourceManager.GetString("CONFIGURE_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Convocatoria:.
        /// </summary>
        internal static string CONVOCATORIA_ADD_TITLE {
            get {
                return ResourceManager.GetString("CONVOCATORIA_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Convocatoria:.
        /// </summary>
        internal static string CONVOCATORIA_EDIT_TITLE {
            get {
                return ResourceManager.GetString("CONVOCATORIA_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Cronograma:.
        /// </summary>
        internal static string CRONOGRAMA_ADD_TITLE {
            get {
                return ResourceManager.GetString("CRONOGRAMA_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Cronograma: .
        /// </summary>
        internal static string CRONOGRAMA_EDIT_TITLE {
            get {
                return ResourceManager.GetString("CRONOGRAMA_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cronogramas.
        /// </summary>
        internal static string CRONOGRAMAS {
            get {
                return ResourceManager.GetString("CRONOGRAMAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Curso:.
        /// </summary>
        internal static string CURSO_ADD_TITLE {
            get {
                return ResourceManager.GetString("CURSO_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Curso:.
        /// </summary>
        internal static string CURSO_EDIT_TITLE {
            get {
                return ResourceManager.GetString("CURSO_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Cursos:.
        /// </summary>
        internal static string CURSO_FIND_TITLE {
            get {
                return ResourceManager.GetString("CURSO_FIND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursos.
        /// </summary>
        internal static string CURSOS {
            get {
                return ResourceManager.GetString("CURSOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Departamento:.
        /// </summary>
        internal static string DEPARTAMENTO_ADD_TITLE {
            get {
                return ResourceManager.GetString("DEPARTAMENTO_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Departamento:.
        /// </summary>
        internal static string DEPARTAMENTO_EDIT_TITLE {
            get {
                return ResourceManager.GetString("DEPARTAMENTO_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Departamentos:.
        /// </summary>
        internal static string DEPARTAMENTO_FIND_TITLE {
            get {
                return ResourceManager.GetString("DEPARTAMENTO_FIND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departamentos:.
        /// </summary>
        internal static string DEPARTAMENTOS {
            get {
                return ResourceManager.GetString("DEPARTAMENTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discrepancias:.
        /// </summary>
        internal static string DISCREPANCIA_TITLE {
            get {
                return ResourceManager.GetString("DISCREPANCIA_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Disponibilidad:.
        /// </summary>
        internal static string DISPONIBILIDAD_ADD_TITLE {
            get {
                return ResourceManager.GetString("DISPONIBILIDAD_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Disponibilidad:.
        /// </summary>
        internal static string DISPONIBILIDAD_EDIT_TITLE {
            get {
                return ResourceManager.GetString("DISPONIBILIDAD_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicar Capacidad:.
        /// </summary>
        internal static string DUPLICAR_CAPACIDAD_TITLE {
            get {
                return ResourceManager.GetString("DUPLICAR_CAPACIDAD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Empleado:.
        /// </summary>
        internal static string EMPLEADO_ADD_TITLE {
            get {
                return ResourceManager.GetString("EMPLEADO_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Empleado:.
        /// </summary>
        internal static string EMPLEADO_EDIT_TITLE {
            get {
                return ResourceManager.GetString("EMPLEADO_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Empleados:.
        /// </summary>
        internal static string EMPLEADO_FIND_TITLE {
            get {
                return ResourceManager.GetString("EMPLEADO_FIND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empleados.
        /// </summary>
        internal static string EMPLEADOS {
            get {
                return ResourceManager.GetString("EMPLEADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Escuela.
        /// </summary>
        internal static string EMPRESA_ADD_TITLE {
            get {
                return ResourceManager.GetString("EMPRESA_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle de Escuela:.
        /// </summary>
        internal static string EMPRESA_DETAIL_TITLE {
            get {
                return ResourceManager.GetString("EMPRESA_DETAIL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Escuela:.
        /// </summary>
        internal static string EMPRESA_EDIT_TITLE {
            get {
                return ResourceManager.GetString("EMPRESA_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Escuela.
        /// </summary>
        internal static string EMPRESA_LOCALIZE_TITLE {
            get {
                return ResourceManager.GetString("EMPRESA_LOCALIZE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escuelas.
        /// </summary>
        internal static string EMPRESAS {
            get {
                return ResourceManager.GetString("EMPRESAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ERROR_TITLE {
            get {
                return ResourceManager.GetString("ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Examen:.
        /// </summary>
        internal static string EXAMEN_ADD_TITLE {
            get {
                return ResourceManager.GetString("EXAMEN_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Examen:.
        /// </summary>
        internal static string EXAMEN_EDIT_TITLE {
            get {
                return ResourceManager.GetString("EXAMEN_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Exámenes:.
        /// </summary>
        internal static string EXAMEN_FIND_TITLE {
            get {
                return ResourceManager.GetString("EXAMEN_FIND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exámenes:.
        /// </summary>
        internal static string EXAMENES {
            get {
                return ResourceManager.GetString("EXAMENES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clases Extra:.
        /// </summary>
        internal static string EXTRAS_TITLE {
            get {
                return ResourceManager.GetString("EXTRAS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Factura:.
        /// </summary>
        internal static string FACTURA_ADD_TITLE {
            get {
                return ResourceManager.GetString("FACTURA_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturas Cobradas.
        /// </summary>
        internal static string FACTURA_COBRADAS {
            get {
                return ResourceManager.GetString("FACTURA_COBRADAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle de Factura:.
        /// </summary>
        internal static string FACTURA_DETAIL_TITLE {
            get {
                return ResourceManager.GetString("FACTURA_DETAIL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Factura:.
        /// </summary>
        internal static string FACTURA_EDIT_TITLE {
            get {
                return ResourceManager.GetString("FACTURA_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Factura.
        /// </summary>
        internal static string FACTURA_LOCALIZE_TITLE {
            get {
                return ResourceManager.GetString("FACTURA_LOCALIZE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturas Pendientes.
        /// </summary>
        internal static string FACTURA_PENDIENTES {
            get {
                return ResourceManager.GetString("FACTURA_PENDIENTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todas las Facturas.
        /// </summary>
        internal static string FACTURA_TODAS {
            get {
                return ResourceManager.GetString("FACTURA_TODAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Faltas de Alumnos:.
        /// </summary>
        internal static string FALTAS_ALUMNOS_VIEW_TITLE {
            get {
                return ResourceManager.GetString("FALTAS_ALUMNOS_VIEW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo horario:.
        /// </summary>
        internal static string HORARIO_ADD_TITLE {
            get {
                return ResourceManager.GetString("HORARIO_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Horario:.
        /// </summary>
        internal static string HORARIO_EDIT_TITLE {
            get {
                return ResourceManager.GetString("HORARIO_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Horarios:.
        /// </summary>
        internal static string HORARIO_FIND_TITLE {
            get {
                return ResourceManager.GetString("HORARIO_FIND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horarios.
        /// </summary>
        internal static string HORARIOS {
            get {
                return ResourceManager.GetString("HORARIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Imagen de Pregunta:.
        /// </summary>
        internal static string IMAGEN_PREGUNTA_VIEW_TITLE {
            get {
                return ResourceManager.GetString("IMAGEN_PREGUNTA_VIEW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir Incidencia.
        /// </summary>
        internal static string INCIDENCIA_ADD_TITLE {
            get {
                return ResourceManager.GetString("INCIDENCIA_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles de la Incidencia.
        /// </summary>
        internal static string INCIDENCIA_DETAIL_TITLE {
            get {
                return ResourceManager.GetString("INCIDENCIA_DETAIL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Incidencia.
        /// </summary>
        internal static string INCIDENCIA_EDIT_TITLE {
            get {
                return ResourceManager.GetString("INCIDENCIA_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe de Acciones Correctoras:.
        /// </summary>
        internal static string INFORME_ACCION_CORRECTORA_TITLE {
            get {
                return ResourceManager.GetString("INFORME_ACCION_CORRECTORA_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe de Ampliación:.
        /// </summary>
        internal static string INFORME_AMPLIACION_TITLE {
            get {
                return ResourceManager.GetString("INFORME_AMPLIACION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe de Discrepancias:.
        /// </summary>
        internal static string INFORME_DISCREPANCIA_TITLE {
            get {
                return ResourceManager.GetString("INFORME_DISCREPANCIA_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Empleado:.
        /// </summary>
        internal static string INSTRUCTOR_ADD_TITLE {
            get {
                return ResourceManager.GetString("INSTRUCTOR_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Empleado:.
        /// </summary>
        internal static string INSTRUCTOR_EDIT_TITLE {
            get {
                return ResourceManager.GetString("INSTRUCTOR_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Empleados:.
        /// </summary>
        internal static string INSTRUCTOR_FIND_TITLE {
            get {
                return ResourceManager.GetString("INSTRUCTOR_FIND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empleados.
        /// </summary>
        internal static string INSTRUCTORES {
            get {
                return ResourceManager.GetString("INSTRUCTORES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir Inventario.
        /// </summary>
        internal static string INVENTARIOALMACEN_ADD_TITLE {
            get {
                return ResourceManager.GetString("INVENTARIOALMACEN_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles del Inventario.
        /// </summary>
        internal static string INVENTARIOALMACEN_DETAIL_TITLE {
            get {
                return ResourceManager.GetString("INVENTARIOALMACEN_DETAIL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Inventario.
        /// </summary>
        internal static string INVENTARIOALMACEN_EDIT_TITLE {
            get {
                return ResourceManager.GetString("INVENTARIOALMACEN_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1 Ayuda.
        /// </summary>
        internal static string LEYENDA {
            get {
                return ResourceManager.GetString("LEYENDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir Línea de Pedido.
        /// </summary>
        internal static string LINEAPEDIDO_ADD_TITLE {
            get {
                return ResourceManager.GetString("LINEAPEDIDO_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detallar Línea de Pedido.
        /// </summary>
        internal static string LINEAPEDIDO_DETAIL_TITLE {
            get {
                return ResourceManager.GetString("LINEAPEDIDO_DETAIL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Línea de Pedido.
        /// </summary>
        internal static string LINEAPEDIDO_EDIT_TITLE {
            get {
                return ResourceManager.GetString("LINEAPEDIDO_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Material:.
        /// </summary>
        internal static string MATERIAL_ADD_TITLE {
            get {
                return ResourceManager.GetString("MATERIAL_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Material Docente:.
        /// </summary>
        internal static string MATERIAL_EDIT_TITLE {
            get {
                return ResourceManager.GetString("MATERIAL_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Materiales:.
        /// </summary>
        internal static string MATERIAL_FIND_TITLE {
            get {
                return ResourceManager.GetString("MATERIAL_FIND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Docente.
        /// </summary>
        internal static string MATERIALES {
            get {
                return ResourceManager.GetString("MATERIALES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Módulo:.
        /// </summary>
        internal static string MODULO_ADD_TITLE {
            get {
                return ResourceManager.GetString("MODULO_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Módulo:.
        /// </summary>
        internal static string MODULO_EDIT_TITLE {
            get {
                return ResourceManager.GetString("MODULO_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Módulos:.
        /// </summary>
        internal static string MODULO_FIND_TITLE {
            get {
                return ResourceManager.GetString("MODULO_FIND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulos.
        /// </summary>
        internal static string MODULOS {
            get {
                return ResourceManager.GetString("MODULOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipios:.
        /// </summary>
        internal static string MUNICIPIO_TITLE {
            get {
                return ResourceManager.GetString("MUNICIPIO_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Nota de alumno:.
        /// </summary>
        internal static string NOTA_ALUMNO_TITLE {
            get {
                return ResourceManager.GetString("NOTA_ALUMNO_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notas de Alumnos.
        /// </summary>
        internal static string NOTAS_ALUMNOS {
            get {
                return ResourceManager.GetString("NOTAS_ALUMNOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar Orden de la Clase:.
        /// </summary>
        internal static string ORDENAR_CLASES_TITLE {
            get {
                return ResourceManager.GetString("ORDENAR_CLASES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar Orden:.
        /// </summary>
        internal static string ORDENAR_PREGUNTAS_EXAMEN_TITLE {
            get {
                return ResourceManager.GetString("ORDENAR_PREGUNTAS_EXAMEN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Parte de Asistencia:.
        /// </summary>
        internal static string P_ASISTENCIA_ADD_TITLE {
            get {
                return ResourceManager.GetString("P_ASISTENCIA_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Parte de Asistencia:.
        /// </summary>
        internal static string P_ASISTENCIA_EDIT_TITLE {
            get {
                return ResourceManager.GetString("P_ASISTENCIA_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Partes de Asistencia:.
        /// </summary>
        internal static string P_ASISTENCIA_FIND_TITLE {
            get {
                return ResourceManager.GetString("P_ASISTENCIA_FIND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir Pedido.
        /// </summary>
        internal static string PEDIDOPROVEEDOR_ADD_TITLE {
            get {
                return ResourceManager.GetString("PEDIDOPROVEEDOR_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles del pedido.
        /// </summary>
        internal static string PEDIDOPROVEEDOR_DETAIL_TITLE {
            get {
                return ResourceManager.GetString("PEDIDOPROVEEDOR_DETAIL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Pedido.
        /// </summary>
        internal static string PEDIDOPROVEEDOR_EDIT_TITLE {
            get {
                return ResourceManager.GetString("PEDIDOPROVEEDOR_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Plan Anual de Auditorías:.
        /// </summary>
        internal static string PLAN_ANUAL_ADD_TITLE {
            get {
                return ResourceManager.GetString("PLAN_ANUAL_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Plan Anual de Auditorías:.
        /// </summary>
        internal static string PLAN_ANUAL_EDIT_TITLE {
            get {
                return ResourceManager.GetString("PLAN_ANUAL_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Planes Anuales de Auditorías:.
        /// </summary>
        internal static string PLAN_ANUAL_FIND_TITLE {
            get {
                return ResourceManager.GetString("PLAN_ANUAL_FIND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Plan de Estudios:.
        /// </summary>
        internal static string PLAN_DOCENTE_ADD_TITLE {
            get {
                return ResourceManager.GetString("PLAN_DOCENTE_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Plan de Estudios:.
        /// </summary>
        internal static string PLAN_DOCENTE_EDIT_TITLE {
            get {
                return ResourceManager.GetString("PLAN_DOCENTE_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Planes de Estudios:.
        /// </summary>
        internal static string PLAN_DOCENTE_FIND_TITLE {
            get {
                return ResourceManager.GetString("PLAN_DOCENTE_FIND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Plan Extra:.
        /// </summary>
        internal static string PLAN_EXTRA_ADD_TITLE {
            get {
                return ResourceManager.GetString("PLAN_EXTRA_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Plan Extra:.
        /// </summary>
        internal static string PLAN_EXTRA_EDIT_TITLE {
            get {
                return ResourceManager.GetString("PLAN_EXTRA_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Planes Extra:.
        /// </summary>
        internal static string PLAN_EXTRA_FIND_TITLE {
            get {
                return ResourceManager.GetString("PLAN_EXTRA_FIND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planes Anuales:.
        /// </summary>
        internal static string PLANES_ANUALES {
            get {
                return ResourceManager.GetString("PLANES_ANUALES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planes de Estudios.
        /// </summary>
        internal static string PLANES_DOCENTES {
            get {
                return ResourceManager.GetString("PLANES_DOCENTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planes Extra.
        /// </summary>
        internal static string PLANES_EXTRA {
            get {
                return ResourceManager.GetString("PLANES_EXTRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plantillas de Exámenes.
        /// </summary>
        internal static string PLANTILLA_EXAMEN {
            get {
                return ResourceManager.GetString("PLANTILLA_EXAMEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Plantilla de Examen:.
        /// </summary>
        internal static string PLANTILLA_EXAMEN_ADD_TITLE {
            get {
                return ResourceManager.GetString("PLANTILLA_EXAMEN_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Plantilla de Examen:.
        /// </summary>
        internal static string PLANTILLA_EXAMEN_EDIT_TITLE {
            get {
                return ResourceManager.GetString("PLANTILLA_EXAMEN_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Plantillas de Exámenes:.
        /// </summary>
        internal static string PLANTILLA_FIND_TITLE {
            get {
                return ResourceManager.GetString("PLANTILLA_FIND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered by iQ.
        /// </summary>
        internal static string POWEREDBY {
            get {
                return ResourceManager.GetString("POWEREDBY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clases Prácticas:.
        /// </summary>
        internal static string PRACTICAS_TITLE {
            get {
                return ResourceManager.GetString("PRACTICAS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Pregunta:.
        /// </summary>
        internal static string PREGUNTA_ADD_TITLE {
            get {
                return ResourceManager.GetString("PREGUNTA_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Pregunta:.
        /// </summary>
        internal static string PREGUNTA_EDIT_TITLE {
            get {
                return ResourceManager.GetString("PREGUNTA_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Preguntas:.
        /// </summary>
        internal static string PREGUNTA_FIND_TITLE {
            get {
                return ResourceManager.GetString("PREGUNTA_FIND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preguntas.
        /// </summary>
        internal static string PREGUNTAS {
            get {
                return ResourceManager.GetString("PREGUNTAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Preguntas:.
        /// </summary>
        internal static string PREGUNTAS_PLANTILLA_TITLE {
            get {
                return ResourceManager.GetString("PREGUNTAS_PLANTILLA_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimir.
        /// </summary>
        internal static string PRINT_TITLE {
            get {
                return ResourceManager.GetString("PRINT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Promoción:.
        /// </summary>
        internal static string PROMOCION_ADD_TITLE {
            get {
                return ResourceManager.GetString("PROMOCION_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Promoción:.
        /// </summary>
        internal static string PROMOCION_EDIT_TITLE {
            get {
                return ResourceManager.GetString("PROMOCION_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Promociones:.
        /// </summary>
        internal static string PROMOCION_FIND_TITLE {
            get {
                return ResourceManager.GetString("PROMOCION_FIND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promociones.
        /// </summary>
        internal static string PROMOCIONES {
            get {
                return ResourceManager.GetString("PROMOCIONES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Proveedor.
        /// </summary>
        internal static string PROVEEDOR_ADD_TITLE {
            get {
                return ResourceManager.GetString("PROVEEDOR_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles del Proveedor.
        /// </summary>
        internal static string PROVEEDOR_DETAIL_TITLE {
            get {
                return ResourceManager.GetString("PROVEEDOR_DETAIL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Proveedor.
        /// </summary>
        internal static string PROVEEDOR_EDIT_TITLE {
            get {
                return ResourceManager.GetString("PROVEEDOR_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puntos del Acta del Comité de Calidad.
        /// </summary>
        internal static string PUNTOS_ACTAS_TITLE {
            get {
                return ResourceManager.GetString("PUNTOS_ACTAS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respuestas:.
        /// </summary>
        internal static string RESPUESTAS_TITLE {
            get {
                return ResourceManager.GetString("RESPUESTAS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar Copia de Seguridad:.
        /// </summary>
        internal static string RESTORE_BACKUP_TITLE {
            get {
                return ResourceManager.GetString("RESTORE_BACKUP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumen Examen.
        /// </summary>
        internal static string RESUMEN_EXAMEN_TITLE {
            get {
                return ResourceManager.GetString("RESUMEN_EXAMEN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar alumnos:.
        /// </summary>
        internal static string SELECT_ALUMNOS {
            get {
                return ResourceManager.GetString("SELECT_ALUMNOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar Plantilla de Examen.
        /// </summary>
        internal static string SELECT_PLANTILLA {
            get {
                return ResourceManager.GetString("SELECT_PLANTILLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar Preguntas:.
        /// </summary>
        internal static string SELECT_PREGUNTAS {
            get {
                return ResourceManager.GetString("SELECT_PREGUNTAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir Servicio.
        /// </summary>
        internal static string SERVICIOCLIENTE_ADD_TITLE {
            get {
                return ResourceManager.GetString("SERVICIOCLIENTE_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles del Servicio.
        /// </summary>
        internal static string SERVICIOCLIENTE_DETAIL_TITLE {
            get {
                return ResourceManager.GetString("SERVICIOCLIENTE_DETAIL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Servicio.
        /// </summary>
        internal static string SERVICIOCLIENTE_EDIT_TITLE {
            get {
                return ResourceManager.GetString("SERVICIOCLIENTE_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Servicio.
        /// </summary>
        internal static string SERVICIOCLIENTE_FIND_TITLE {
            get {
                return ResourceManager.GetString("SERVICIOCLIENTE_FIND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir Servicio.
        /// </summary>
        internal static string SERVICIOPROVEEDOR_ADD_TITLE {
            get {
                return ResourceManager.GetString("SERVICIOPROVEEDOR_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles del Servicio.
        /// </summary>
        internal static string SERVICIOPROVEEDOR_DETAIL_TITLE {
            get {
                return ResourceManager.GetString("SERVICIOPROVEEDOR_DETAIL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Servicio.
        /// </summary>
        internal static string SERVICIOPROVEEDOR_EDIT_TITLE {
            get {
                return ResourceManager.GetString("SERVICIOPROVEEDOR_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Servicio.
        /// </summary>
        internal static string SERVICIOPROVEEDOR_FIND_TITLE {
            get {
                return ResourceManager.GetString("SERVICIOPROVEEDOR_FIND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Submódulo:.
        /// </summary>
        internal static string SUBMODULO_ADD_TITLE {
            get {
                return ResourceManager.GetString("SUBMODULO_ADD_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar Submódulo:.
        /// </summary>
        internal static string SUBMODULO_EDIT_TITLE {
            get {
                return ResourceManager.GetString("SUBMODULO_EDIT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Asignación de Submódulos por Instructor:.
        /// </summary>
        internal static string SUBMODULO_INSTRUCTOR_PROMOCION_VIEW_TITLE {
            get {
                return ResourceManager.GetString("SUBMODULO_INSTRUCTOR_PROMOCION_VIEW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temas:.
        /// </summary>
        internal static string TEMA_TITLE {
            get {
                return ResourceManager.GetString("TEMA_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clases Teóricas:.
        /// </summary>
        internal static string TEORICAS_TITLE {
            get {
                return ResourceManager.GetString("TEORICAS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos de Auditorías:.
        /// </summary>
        internal static string TIPO_AUDITORIA_TITLE {
            get {
                return ResourceManager.GetString("TIPO_AUDITORIA_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Preguntas:.
        /// </summary>
        internal static string VER_PREGUNTAS_TITLE {
            get {
                return ResourceManager.GetString("VER_PREGUNTAS_TITLE", resourceCulture);
            }
        }
    }
}
